import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./Providers";
import "@rainbow-me/rainbowkit/styles.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "CrowdFund OnChain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="min-h-screen flex flex-col bg-gray-900 ">
            <Navbar />
            <main className="flex-1 flex justify-center ">
              {children}
            </main>
            <Toaster />
          </div>
        </Providers>
      </body>
    </html>
  );
}
