import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./Providers";
import "@rainbow-me/rainbowkit/styles.css";
import Navbar from "@/components/Navbar";
export const metadata: Metadata = {
  title: "GoFundMe OnChain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
